# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import battle_pb2 as battle__pb2


class DefenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MissileApproaching = channel.unary_unary(
                '/Defender/MissileApproaching',
                request_serializer=battle__pb2.MissileNotification.SerializeToString,
                response_deserializer=battle__pb2.TrackingDetails.FromString,
                )
        self.InitializeSoldiers = channel.unary_unary(
                '/Defender/InitializeSoldiers',
                request_serializer=battle__pb2.InitReq.SerializeToString,
                response_deserializer=battle__pb2.InitDetails.FromString,
                )


class DefenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MissileApproaching(self, request, context):
        """Notify the soldiers about an approaching missile.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeSoldiers(self, request, context):
        """Query soldier details to keep track of .
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DefenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MissileApproaching': grpc.unary_unary_rpc_method_handler(
                    servicer.MissileApproaching,
                    request_deserializer=battle__pb2.MissileNotification.FromString,
                    response_serializer=battle__pb2.TrackingDetails.SerializeToString,
            ),
            'InitializeSoldiers': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeSoldiers,
                    request_deserializer=battle__pb2.InitReq.FromString,
                    response_serializer=battle__pb2.InitDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Defender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Defender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MissileApproaching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Defender/MissileApproaching',
            battle__pb2.MissileNotification.SerializeToString,
            battle__pb2.TrackingDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitializeSoldiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Defender/InitializeSoldiers',
            battle__pb2.InitReq.SerializeToString,
            battle__pb2.InitDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
