# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61ttle.proto\"\x1f\n\x07InitReq\x12\t\n\x01N\x18\x01 \x01(\x05\x12\t\n\x01T\x18\x02 \x01(\x05\"L\n\x13MissileNotification\x12\t\n\x01t\x18\x01 \x01(\x05\x12\x14\n\x0cmissile_type\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x05\x12\t\n\x01y\x18\x04 \x01(\x05\"@\n\x0fTrackingDetails\x12\x16\n\x0e\x63\x61sualty_count\x18\x01 \x01(\x05\x12\x15\n\rsoldier_count\x18\x02 \x01(\x05\"f\n\rSoldierDetail\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05speed\x18\x04 \x01(\x05\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x14\n\x0cis_commander\x18\x06 \x01(\x08\"2\n\x0bInitDetails\x12#\n\x0bsol_details\x18\x01 \x03(\x0b\x32\x0e.SoldierDetail2v\n\x08\x44\x65\x66\x65nder\x12<\n\x12MissileApproaching\x12\x14.MissileNotification\x1a\x10.TrackingDetails\x12,\n\x12InitializeSoldiers\x12\x08.InitReq\x1a\x0c.InitDetailsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INITREQ']._serialized_start=16
  _globals['_INITREQ']._serialized_end=47
  _globals['_MISSILENOTIFICATION']._serialized_start=49
  _globals['_MISSILENOTIFICATION']._serialized_end=125
  _globals['_TRACKINGDETAILS']._serialized_start=127
  _globals['_TRACKINGDETAILS']._serialized_end=191
  _globals['_SOLDIERDETAIL']._serialized_start=193
  _globals['_SOLDIERDETAIL']._serialized_end=295
  _globals['_INITDETAILS']._serialized_start=297
  _globals['_INITDETAILS']._serialized_end=347
  _globals['_DEFENDER']._serialized_start=349
  _globals['_DEFENDER']._serialized_end=467
# @@protoc_insertion_point(module_scope)
